services:
  psql:
    ports: []
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/prod:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    env_file:
      - ./.env
    depends_on:
      deploy-lab:
        condition: service_healthy
    networks:
      - internal
  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    env_file:
      - ./.env
    depends_on:
      - nginx
    networks:
      - internal
