services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/dev:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:rw
    env_file:
      - ./.env
    depends_on:
      deploy-lab:
        condition: service_healthy
    networks:
      - internal
