services:
  nginx:
    image: nginx:1.29.5-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/dev:/etc/nginx/conf.d:ro
      - ./nginx/certs/dev:/etc/nginx/certs:rw
      - ./scripts/nginx-entrypoint.sh:/scripts/nginx-entrypoint.sh:ro
    entrypoint: ["/scripts/nginx-entrypoint.sh"]
    depends_on:
      deploy-lab:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - internal
