#!/usr/bin/env bash

set -eu

# Nginx entrypoint for local development with HTTPS.
#
# Responsibilities:
# - Generate a self-signed TLS certificate if it does not exist.
# - Start nginx.
# - Periodically reload nginx to pick up config or renewed certificates.
#
# Environment variables:
# - DOMAIN: Common Name (CN) used in the self-signed certificate (default: localhost).
# - NGINX_RELOAD_INTERVAL: Sleep interval between reloads (default: 6h, accepts formats like "10s", "5m", "2h").
#
# Config for conf.d is generated by scripts/setup.sh before starting containers.

DOMAIN="${DOMAIN:-localhost}"

CERT_DIR="/etc/nginx/certs"
CRT="${CERT_DIR}/dev.crt"
KEY="${CERT_DIR}/dev.key"

# If /etc/nginx/certs exists, assume this container is responsible for managing the TLS certificate.
if [ -d "$CERT_DIR" ]; then
  # Only generate a certificate when one does not already exist.
  if [ ! -f "$CRT" ] || [ ! -f "$KEY" ]; then
    echo "[nginx] Generating self-signed certificate for ${DOMAIN}..."

    # Ensure openssl is installed (nginx:alpine uses apk as package manager).
    if ! command -v openssl >/dev/null 2>&1; then
      apk add --no-cache openssl >/dev/null
    fi

    # Long-lived self-signed certificate for local development.
    openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
      -keyout "$KEY" \
      -out "$CRT" \
      -subj "/CN=${DOMAIN}"
  fi
fi

echo "[nginx] Starting nginx..."
nginx

# Periodically reload nginx to pick up config changes or renewed certificates.
RELOAD_INTERVAL="${NGINX_RELOAD_INTERVAL:-6h}"

while :; do
  sleep "$RELOAD_INTERVAL"
  echo "[nginx] Reloading nginx..."
  nginx -s reload || true
done
